name: carb_manager_assignment
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  redux_epics: ^0.15.1
  rxdart: ^0.27.3
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  retrofit: ^3.0.1+1
  retry: ^3.1.0
  dio: ^4.0.4
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true
  assets:
    - res/